controller_joint_names: ['', 'shoulder_fr_j', 'leg_fr_j', 'foreleg_fr_j', 'shoulder_fl_j', 'leg_fl_j', 'foreleg_fl_j', 'shoulder_br_j', 'leg_br_j', 'foreleg_br_j', 'shoulder_bl_j', 'leg_bl_j', 'foreleg_bl_j', ]
